---
dist: trusty
addons:
  chrome: stable
language: node_js

node_js:
  - lts/carbon

cache:
  directories:
    - $HOME/.npm

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - npm install -g bower
  - npm install
  - bower install
